name: Java CI

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          version: [17]
          os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
      - name: test_order_consumer
        run: make test_order_consumer
      - name: test_customer_consumer
        run: make test_customer_consumer
      - name: test_address_provider
        run: make test_address_provider